rule targets:
    input:
        'plots/cell_clusters.pdf',

rule filt_cn:
    input:
        config['copynumber_matrix'],
        config['classified'],
        config['qdnaseq_blacklist']
    output: 'output/filt_cn.tsv'
    shell:
        '''
        filter_copynumber {input[0]} {output} \
            --cell-scores {input[1]} --qdnaseq-blacklist {input[2]} \
            --filter-contig-dup-bins
        '''

rule cell_clusters:
    input: 'output/filt_cn.tsv'
    output:
        'output/cell_clusters.tsv',
        'plots/cell_clusters.pdf'
    shell: 'cluster_cells {input} {output[0]} --plot {output[1]}'
