rule targets:
    input:
        'plots/cell_clusters.pdf',

rule filt_cell_cn:
    input:
        config['copynumber_matrix'],
        config['classified']
    output: 'output/filt-cell_cn.tsv'
    shell: 'filter_copynumber_cells {input} {output}'

rule filt_bin_cn:
    input:
        'output/filt-cell_cn.tsv',
        config['qdnaseq_blacklist']
    output: 'output/filt-cell_filt-bin_cn.tsv'
    shell: 'filter_copynumber_bins {input} {output}'

rule filt_dup_cn:
    input: 'output/filt-cell_filt-bin_cn.tsv',
    output: 'output/filt-cell_filt-bin_filt-dup_cn.tsv'
    shell: 'filter_copynumber_contiguous_duplicate_bins {input} {output}'

rule cell_clusters:
    input: 'output/filt-cell_filt-bin_filt-dup_cn.tsv'
    output:
        'output/cell_clusters.tsv',
        'plots/cell_clusters.pdf'
    shell: 'cluster_cells {input} {output[0]} --plot {output[1]}'
